---
server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /var/promtail/positions.yaml

client:
  url: http://<loki_debug_host>:3200/api/prom/push

scrape_configs:
  - job_name: <job_name>
    pipeline_stages:
      - regex:
          expression: (?P<dt>\d{4}-\d{2}-\d{2}\ [\ ]*\d{1,2}:\d{2}:\d{2})\ (?P<id>\d+)\ \[(?P<level>.+)\]\ (?P<message>.+)
      - timestamp:
          source: dt
          format: '2006-01-02 15:04:05'
          location: Europe/Berlin
      - labels:
          level:
    static_configs:
      - labels:
          job: <source_job_name>
          host: <host>
          __path__: /root/promtail-dev/sample
